server:
  port: 8080

postgres:
  host: localhost
  port: 5433
  db:
    name: delivery
  username: user
  password: admin

spring:

  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.db.name}
    username: ${postgres.username}
    password: ${postgres.password}

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    properties.hibernate.format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL81Dialect